const authClient=supabaseClient;
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function getNextPage(){const next=new URLSearchParams(location.search).get("next");return next&&/^[a-zA-Z0-9_-]+\.html(?:#[^]*)?$/.test(next)?next:"account.html";}
async function updateAccountLinks(){const {data:{session}}=await authClient.auth.getSession();document.querySelectorAll("[data-account-link]").forEach(link=>{link.href=session?"account.html":"login.html";link.textContent=session?"My Account":"Sign in";});}
async function cancelOrder(id,number){if(!confirm("Cancel order #"+number+"? This can only be done before payment is completed."))return;const {error}=await authClient.from("orders").update({status:"cancelled",cancelled_at:new Date().toISOString(),cancellation_reason:"Cancelled by customer"}).eq("id",id).eq("status","pending");if(error){alert("Unable to cancel this order: "+error.message);return;}location.reload();}
async function initAuthPage(){updateAccountLinks();const path=location.pathname.split("/").pop();
if(path==="login.html"){const {data:{session}}=await authClient.auth.getSession();if(session){location.href=getNextPage();return;}document.getElementById("login-form").addEventListener("submit",async e=>{e.preventDefault();const m=document.getElementById("auth-message");m.textContent="Signing in...";const {error}=await authClient.auth.signInWithPassword({email:document.getElementById("email").value.trim(),password:document.getElementById("password").value});if(error){m.textContent=error.message;return;}location.href=getNextPage();});}
else if(path==="register.html"){document.getElementById("register-form").addEventListener("submit",async e=>{e.preventDefault();const m=document.getElementById("auth-message"),p=document.getElementById("password").value;if(p!==document.getElementById("confirm").value){m.textContent="Passwords do not match.";return;}m.textContent="Creating account...";const {data,error}=await authClient.auth.signUp({email:document.getElementById("email").value.trim(),password:p,options:{data:{full_name:document.getElementById("name").value.trim()}}});if(error){m.textContent=error.message;return;}if(data.session)location.href=getNextPage();else m.textContent="Account created. Please check your email to confirm your account, then sign in.";});}
else if(path==="account.html"){const {data:{session}}=await authClient.auth.getSession();if(!session){location.href="login.html?next=account.html";return;}document.getElementById("account-email").textContent=session.user.email||"";const {data:orders,error}=await authClient.from("orders").select("*").eq("user_id",session.user.id).order("created_at",{ascending:false});const box=document.getElementById("orders-list");if(error)box.innerHTML='<div class="card"><p>Unable to load your orders. Please try again later.</p></div>';else if(!orders.length)box.innerHTML='<div class="card empty-account"><p>You have no orders yet.</p><a class="btn" href="index.html#products">Start shopping</a></div>';else box.innerHTML=orders.map(o=>{const status=(o.status||"pending").toLowerCase();const cancel=status==="pending"?"<button class=\"small-btn cancel-order-btn\" type=\"button\" onclick=\"cancelOrder('"+esc(o.id)+"','"+esc(o.order_number||o.id)+"')\">Cancel order</button>":"";return '<article class="card account-order"><div><p class="eyebrow">Order</p><h2>#'+esc(o.order_number||o.id)+'</h2><small>'+esc(o.customer_name||"")+'</small></div><div class="account-order-meta"><span>'+esc(status)+'</span><strong>$'+Number(o.total||0).toFixed(2)+'</strong><small>'+new Date(o.created_at).toLocaleString()+'</small>'+cancel+'</div></article>';}).join("");const signout=async()=>{await authClient.auth.signOut();location.href="index.html";};document.getElementById("logout").onclick=signout;document.getElementById("footer-logout").onclick=signout;}}
window.cancelOrder=cancelOrder;
initAuthPage();