const authClient=supabaseClient;
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function getNextPage(){const next=new URLSearchParams(location.search).get("next");return next&&/^[a-zA-Z0-9_-]+\.html(?:#[^]*)?$/.test(next)?next:"account.html";}
async function updateAccountLinks(){const {data:{session}}=await authClient.auth.getSession();document.querySelectorAll("[data-account-link]").forEach(link=>{link.href=session?"account.html":"login.html";link.textContent=session?"My Account":"Sign in";});}
function toggleOrderDetails(id,button){const el=document.getElementById(id);if(!el)return;const open=!el.hidden;el.hidden=open;button.textContent=open?"View details":"Hide details";}
async function cancelOrder(id,number){if(!confirm("Cancel order #"+number+"? This can only be done before payment is completed."))return;const {error}=await authClient.from("orders").update({status:"cancelled",cancelled_at:new Date().toISOString(),cancellation_reason:"Cancelled by customer"}).eq("id",id).eq("status","pending");if(error){alert("Unable to cancel this order: "+error.message);return;}location.reload();}
async function initAuthPage(){updateAccountLinks();const path=location.pathname.split("/").pop();
if(path==="login.html"){const {data:{session}}=await authClient.auth.getSession();if(session){location.href=getNextPage();return;}document.getElementById("login-form").addEventListener("submit",async e=>{e.preventDefault();const m=document.getElementById("auth-message");m.textContent="Signing in...";const {error}=await authClient.auth.signInWithPassword({email:document.getElementById("email").value.trim(),password:document.getElementById("password").value});if(error){m.textContent=error.message;return;}location.href=getNextPage();});}
else if(path==="register.html"){document.getElementById("register-form").addEventListener("submit",async e=>{e.preventDefault();const m=document.getElementById("auth-message"),p=document.getElementById("password").value;if(p!==document.getElementById("confirm").value){m.textContent="Passwords do not match.";return;}m.textContent="Creating account...";const {data,error}=await authClient.auth.signUp({email:document.getElementById("email").value.trim(),password:p,options:{data:{full_name:document.getElementById("name").value.trim()}}});if(error){m.textContent=error.message;return;}if(data.session)location.href=getNextPage();else m.textContent="Account created. Please check your email to confirm your account, then sign in.";});}
else if(path==="account.html"){const {data:{session}}=await authClient.auth.getSession();if(!session){location.href="login.html?next=account.html";return;}document.getElementById("account-email").textContent=session.user.email||"";const {data:orders,error}=await authClient.from("orders").select("*").eq("user_id",session.user.id).order("created_at",{ascending:false});let items=[];const orderIds=(orders||[]).map(o=>o.id);if(!error&&orderIds.length){const itemResult=await authClient.from("order_items").select("order_id,product_name,quantity,unit_price").in("order_id",orderIds);if(!itemResult.error)items=itemResult.data||[];}const box=document.getElementById("orders-list");if(error)box.innerHTML='<div class="card"><p>Unable to load your orders. Please try again later.</p></div>';else if(!orders.length)box.innerHTML='<div class="card empty-account"><p>You have no orders yet.</p><a class="btn" href="index.html#products">Start shopping</a></div>';else box.innerHTML=orders.map(o=>{const status=(o.status||"pending").toLowerCase();const orderItems=items.filter(i=>i.order_id===o.id);const detailsId="order-details-"+o.id;const detailRows=orderItems.length?orderItems.map(i=>"<div class=\"order-item-row\"><span>"+esc(i.product_name||"Product")+"</span><span>"+esc(i.quantity)+" × $"+Number(i.unit_price||0).toFixed(2)+"</span><strong>$"+(Number(i.quantity||0)*Number(i.unit_price||0)).toFixed(2)+"</strong></div>").join(""):"<p class=\"order-empty-detail\">No item details available.</p>";const shipping=[o.shipping_address,o.city,o.country].filter(Boolean).map(esc).join(", ");const details="<div id=\""+detailsId+"\" class=\"order-details\" hidden><div class=\"order-detail-grid\"><div><small>Customer</small><span>"+esc(o.customer_name||"")+"</span></div><div><small>Email</small><span>"+esc(o.customer_email||session.user.email||"")+"</span></div><div><small>Shipping address</small><span>"+(shipping||"—")+"</span></div></div><div class=\"order-items-list\"><div class=\"order-items-head\"><span>Items</span><span>Unit price</span><span>Total</span></div>"+detailRows+"</div></div>";const view="<button class=\"small-btn order-details-btn\" type=\"button\" onclick=\"toggleOrderDetails('"+detailsId+"',this)\">View details</button>";const cancel=status==="pending"?"<button class=\"small-btn cancel-order-btn\" type=\"button\" onclick=\"cancelOrder('"+esc(o.id)+"','"+esc(o.order_number||o.id)+"')\">Cancel order</button>":"";return '<article class="card account-order"><div class="account-order-main"><div><p class="eyebrow">Order</p><h2>#'+esc(o.order_number||o.id)+'</h2><small>'+esc(o.customer_name||"")+'</small></div><div class="account-order-actions">'+view+cancel+'</div></div><div class="account-order-meta"><span>'+esc(status)+'</span><strong>$'+Number(o.total||0).toFixed(2)+'</strong><small>'+new Date(o.created_at).toLocaleString()+'</small></div>'+details+'</article>';}).join("");}}}
window.toggleOrderDetails=toggleOrderDetails;
window.cancelOrder=cancelOrder;
initAuthPage();